media: media
content:
  - name: parroquias
    label: Parroquias
    type: collection
    path: 'parroquias'
    view:
      fields: [ title, location ]
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: cover
        label: Preview image
        type: image
      - name: events
        label: Lista de eventos
        type: object
        fields:
          - name: misas
            label: Misas
            type: object
            list: true
            fields:
              - name: location
                label: Ubicación
                type: select
                options:
                  values: [ Leiza, ..., ... ]
              - name: time
                type: date
                options:
                  time: true
                  step: 900
                label: fecha y hora
              - name: byday
                type: string
                label: repeat
                description: 'LMXJVSD...'
          - name: funerales
            label: Funerales
            type: object
            list: true
            fields:
              - name: location
                type: string
                label: Ubicación
              - name: time
                type: date
                options:
                  time: true
                  step: 900
                label: fecha y hora
          - name: otros
            label: otrsos
            type: object
            list: true
            fields:
              - name: location
                label: Ubicación
                type: select
                options:
                  values: [ Leiza, ..., ... ]
              - name: time
                type: date
                options:
                  time: true
                  step: 900
                label: fecha y hora
              - name: byday
                type: string
                label: repeat
                description: 'LMXJVSD...'
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)