media: media
content:
  - name: herriak
    label: Herriak
    type: collection
    path: herriak
    view:
      fields: [ title, location, name, filename ]
    fields:
      - name: hiletak
        label: Hiletak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
        - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH.mm}}
        - { name: name, label: Hildakoa, type: string }
      - name: ekitaldiak
        label: Ekitaldiak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH.mm}}
          - { name: title, label: Izenburua, type: string }
          - { name: notes, label: Notes, type: text }
          - { name: image, label: Image, type: image }
      - name: mezak
        label: Mezak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.date}" 
        fields:
          - { name: date, type: string, label: "Eguna eta ordua (adib. astelehena 19:00)", patternn: {
            message: Formatu zorrotza izan behar du: astelehenan|astegunetan|... - 09.30 - 3. astea - pazkoa - urtarrila|otsaila|... - 3. astean|hilean|urtean behin,
            regex: '^(astelehenan?|asteartean?|asteazkenan?|ostegunan?|ostiralan?|larunbatetan|igandetan?|astegunetan?|bezperan?)*([ ,-]?([0-9]|0[0-9]|1[0-9]|2[0-3])[:.]([0-5][0-9]))?[ ,-]?([12345]\. astea)?[ ,-]?(pazkoa|urtarrila?k?|otsaila?k?|martxoa?k?|apirila?k?|maiatza?k?|ekaina?k?|uztaila?k?|abuztua?k?|iraila?k?|urria?k?|azaroa?k?|abendua?k?)?[ ,-]?([1-9] (astea?n?|hilea?n?|urtea?n?) behin)?$' } }
          - { name: notes, label: Argibideak, type: string }
          - { name: language, label: hizkuntza,   type: select, default: 'euskaraz', options: { values: [ 'euskaraz', 'erderaz', 'elebidunean' ] } }
      - { name: description, label: Deskribapena, type: string }
      - { name: image, label: Cover image, type: image }
      - { name: gallery, label: Gallery, type: image, list: true }
      - { name: video, label: Youtube, type: string }
      - { name: layout, label: layout, type: string, default: parroquia, hidden: true }
      - name: locations
        label: Tenplu
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: name, label: izena, type: string}
          - { name: geo, label: Geo (lat/log), type: string }
          - { name: image, label: Image, type: image }
      - { name: title, label: Izenburua, type: string }
      - { name: valley, label: valle, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: baliabideak
    label: Baliabideak
    path: baliabideak.md
    type: file
    fields:
      - { name: layout, label: layout, type: string, default: baliabideak, hidden: true }
      - name: sections
        label: sections
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: show, label: show, type: boolean, default: true }
          - { name: title, label: Izenburua, type: string }
          - name: items
            label: items
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{fields.title}" 
            fields:
              - { name: title, label: Izenburua, type: string }
              - { name: yt, label: Youtube code, type: string }
  - name: index
    label: 47herri
    path: index.md
    type: file
    fields:
      - name: ekitaldiak
        label: Ekitaldiak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, label: Eguna eta ordua (adib. astelehena 19:00 edo 25/12/2025), type: string }
          - { name: title, label: Izenburua, type: string }
          - { name: notes, label: Notes, type: text }
          - { name: image, label: Image, type: image }
          - { name: location, label: Herria, type: string }
      - name: hiletak_default
        label: hiletak_default
        type: object
        fields:
          - { name: image, label: Image, type: image }
          - { name: description, label: Deskribapena, type: text }
      - name: mezak_default
        label: mezak_default
        type: object
        fields:
          - { name: image, label: Image, type: image }
      - name: collaborators
        label: Gure apezak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: image, label: Image, type: image }
          - { name: name, label: Izena, type: string }
          - { name: description, label: Deskribapena, type: string }
          - { name: phonenumber, label: Telefonoa, type: string }          
      - { name: layout, label: layout, type: string, default: home, hidden: true }
      - { name: description, label: Webgunearen deskribapena, type: string}
      - { name: image, label: Preview image, type: image}
      - { name: body, label: Body, type: rich-text }