media: media
content:
  - name: herriak
    label: Pueblos
    type: collection
    path: herriak
    view:
      fields: [ title, location, name, filename ]
    fields:
      - name: hiletak
        label: Funerales
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
        - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH.mm, step: 300 }}
        - { name: name, label: Difunto, type: string }
      - name: ekitaldiak
        label: Celebraciones
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH:mm}}
          - { name: title, label: Titulo, type: string }
          - { name: notes, label: Anotaciones, type: text }
          - { name: image, label: Imagen, type: image }
      - name: mezak
        label: Misas regulares
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.date}" 
        fields:
          - { name: date, type: string, label: "Eguna eta ordua (adib. astelehena 19:00)" }
          - { name: cancelled, type: date, label: Cancelaciones, options: { time: false, format: dd/MM/yyyy}}
          - { name: notes, label: Anotaciones, type: string }
          - { name: language, label: Idioma,   type: select, default: 'euskaraz', options: { values: [ 'euskaraz', 'erderaz', 'elebidunean' ] } }
      - { name: description, label: Descripcion, type: string }
      - { name: image, label: Cover image, type: image }
      - { name: gallery, label: Galeria, type: image, list: true }
      - { name: video, label: Youtube, type: string }
      - { name: layout, label: layout, type: string, default: parroquia, hidden: true }
      - name: locations
        label: Templos
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: name, label: Nombre, type: string}
          - { name: geo, label: Geo (lat/log), type: string }
          - { name: image, label: Imagen, type: image }
      - { name: title, label: Izenburua, type: string }
      - { name: valley, label: valle, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: baliabideak
    label: Recursos
    path: baliabideak.md
    type: file
    fields:
      - { name: layout, label: layout, type: string, default: baliabideak, hidden: true }
      - name: sections
        label: sections
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: show, label: show, type: boolean, default: true }
          - { name: title, label: Izenburua, type: string }
          - name: items
            label: items
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{fields.title}" 
            fields:
              - { name: title, label: Izenburua, type: string }
              - { name: yt, label: Youtube code, type: string }
  - name: index
    label: Portada
    path: index.md
    type: file
    fields:
      - name: ekitaldiak
        label: Celebraciones
        description: (añadir evento aqui o en el pueblo especifico, no en ambas)
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, label: Eguna eta ordua (adib. astelehena 19:00 edo 25/12/2025), type: string }
          - { name: title, label: Izenburua, type: string }
          - { name: notes, label: Notes, type: text }
          - { name: image, label: Image, type: image }
          - { name: location, label: Herria, type: string }
      - name: hiletak_default
        label: hiletak_default
        type: object
        fields:
          - { name: image, label: Image, type: image }
          - { name: description, label: Deskribapena, type: text }
      - name: mezak_default
        label: mezak_default
        type: object
        fields:
          - { name: image, label: Image, type: image }
      - name: collaborators
        label: Gure apezak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: image, label: Image, type: image }
          - { name: name, label: Izena, type: string }
          - { name: description, label: Deskribapena, type: string }
          - { name: phonenumber, label: Telefonoa, type: string }          
      - { name: layout, label: layout, type: string, default: home, hidden: true }
      - { name: description, label: Webgunearen deskribapena, type: string}
      - { name: image, label: Preview image, type: image}
      - { name: body, label: Body, type: rich-text }