media: media
content:
  - name: parroquias
    label: Parroquias
    type: collection
    path: 'parroquias'
    view:
      fields: [ title, location ]
    fields:
      - { name: title, label: Website title, type: string }
      - { name: description, label: Website description, type: string }
      - { name: cover, label: Preview image, type: image }
      - name: ermitas
        label: Ermitas y monasterios
        type: object
        list: true
        fields:
          - { name: name, label: Nombre, type: string }
          - { name: geo, label: Geo, type: string }
      - name: events
        label: Lista de eventos
        type: object
        fields:
          - name: misas
            label: Misas
            type: object
            list: true
            fields:
              - { name: time, type: string, label: Hora (ej 19:00), pattern: {
                  message: 'Debe ser un formato de hora válida (ej: 19:00)',
                  regex: '/^([0-9]|0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])$/' }
                }
              - { name: byday, type: string, label: Periodicidad, description: 'L-V (lunes a viernes), SD (sábados y domingos), 1D (primer domingo del mes), V de pascua', pattern: { message: 'Debe ser un formato de hora válida (ej: 19:00)', regex: '/^([1-5]?[LMXJVSD]+[-]*?[LMXJVSD]*?)\s*(de pascua|cada (dos|tres|cuatro|cinco) (semanas|meses|años))?$/' } }
              - { name: notas, label: Notas, type: string }
          - name: funerales
            label: Funerales
            type: object
            list: true
            fields:
              - { name: notas, label: Difunto / Notas, type: string }
              - { name: time, type: date, label: Fecha y hora, options: { time: true}}
          - name: otros
            label: otrsos
            type: object
            list: true
            fields:
              - name: time
                type: date
                options:
                  time: true
                  step: 900
                label: fecha y hora
              - name: byday
                type: string
                label: repeat
                description: 'LMXJVSD...'
      - name: body
        label: Body
        type: rich-text
  - name: hiletak
    label: Hiletak
    path: hiletak.yml
    type: file
    fields:
      - name: hiletak
        label: Hiletak
        type: object
        list: true
        fields:
        - { name: notas, label: Difunto / Notas, type: string }
        - { name: time, type: date, label: Fecha y hora, options: { time: true}}
        - { name: location, label: Ubicación, type: select, options: {
              values: [ Leiza, Lekumberri, Aldatz,... ]}
          }
  - name: config
    label: Settings
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)