media: media
content:
  - name: herriak
    label: Pueblos
    type: collection
    path: herriak
    view:
      fields: [ title, location, name, filename ]
    fields:
      - name: hiletak
        label: Funerales
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
        - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH.mm, step: 300 }}
        - { name: name, label: Difunto, type: string }
      - name: ekitaldiak
        label: Celebraciones especiales
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, type: date, label: Fecha y hora, options: { time: true, format: dd/MM/yyyy HH:mm}}
          - { name: title, label: Titulo, type: string }
          - { name: notes, label: Anotaciones, type: text }
          - { name: image, label: Imagen, type: image }
      - name: mezak
        label: Misas regulares
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.date}" 
        fields:
          - { name: date, type: string, label: "Eguna eta ordua (adib. astelehena 19:00)" }
          - { name: cancelled, type: date, label: Cancelaciones, options: { time: false, format: dd/MM/yyyy}}
          - { name: notes, label: Anotaciones, type: string }
          - { name: language, label: Idioma,   type: select, default: 'euskaraz', options: { values: [ 'euskaraz', 'erderaz', 'elebidunean' ] } }
      - { name: description, label: Descripcion, type: string }
      - { name: image, label: Cover image, type: image }
      - { name: gallery, label: Galeria, type: image, list: true }
      - { name: video, label: Youtube, type: string }
      - { name: layout, label: layout, type: string, default: parroquia, hidden: true }
      - name: locations
        label: Templos
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: name, label: Nombre, type: string}
          - { name: geo, label: Geo (lat/log), type: string }
          - { name: image, label: Imagen, type: image }
      - { name: title, label: Izenburua, type: string }
      - { name: valley, label: valle, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: baliabideak
    label: Recursos
    path: baliabideak.md
    type: file
    fields:
      - { name: layout, label: layout, type: string, default: baliabideak, hidden: true }
      - name: sections
        label: sections
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - { name: show, label: Mostrar sección, type: boolean, default: true }
          - { name: title, label: Titulo sección, type: string }
          - name: items
            label: items
            type: object
            list:
              collapsible:
                collapsed: true
                summary: "{fields.title}" 
            fields:
              - { name: title, label: Titulo video, type: string }
              - { name: yt, label: Código Youtube, type: string }
  - name: index
    label: Portada
    path: index.md
    type: file
    fields:
      - name: ekitaldiak
        label: Celebraciones (añadir evento aqui o en el pueblo especifico, no en ambas)
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}" 
        fields:
          - { name: date, type: string, label: "Día y hora, ej: 15/08/2025 19:00 (Kontuz! usar formato literal)" }
          - { name: title, label: Titulo, type: string }
          - { name: notes, label: Notas, type: text }
          - { name: image, label: Imagen, type: image }
          - { name: location, label: Pueblos, type: reference, options: { collection: herriak, multiple: true, creatable: true, label: "{title}" } }
      - name: hiletak_default
        label: Texto/imagen por defecto de los funerales
        type: object
        fields:
          - { name: image, label: Imagen, type: image }
          - { name: description, label: Oración, type: text }
      - name: mezak_default
        label: Imagen por defecto para horarios de misas
        type: object
        fields:
          - { name: image, label: Image, type: image }
      - name: collaborators
        label: Gure apezak
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.name}" 
        fields:
          - { name: image, label: Imagen, type: image }
          - { name: name, label: Nombre, type: string }
          - { name: description, label: Descriptión/cargo/..., type: string }
          - { name: phonenumber, label: Telefono, type: string }          
      - { name: layout, label: layout, type: string, default: home, hidden: true }
      - { name: description, label: Descripción de la web, type: string}
      - { name: image, label: Imagen, type: image}
      - { name: body, label: Body, type: rich-text }