media: media
content:
  - name: herriak
    label: Herriak
    type: collection
    path: 'herriak'
    view:
      fields: [ title, location ]
    fields:
      - name: hiletak
        label: Hiletak
        type: object
        list: true
        fields:
        - { name: date, type: date, label: Fecha y hora, options: { time: true}}
        - { name: notes, label: Hildakoa edo argibideak, type: string }
      - name: masses
        label: Mezak
        type: object
        list: true
        fields:
          - { name: date, type: string, label: Eguna eta ordua (adib. astelehena 19:00), pattern: {
            message: 'Formatu zorrotza izan behar du: astelehenan|astegunetan|... - 09.30 - 3 astea - pazkoa - urtarrila|otsaila|... - 3 astean|hilean|urtean behin',
            regex: '^(astelehenan?|asteartean?|asteazkenan?|ostegunan?|ostiralan?|larunbatan?|igandean?|astegunetan?|bezperan?)*([ ,-]?([0-9]|0[0-9]|1[0-9]|2[0-3])[:.]([0-5][0-9]))?[ ,-]?(([12345]).? ?astek?o?a)?[ ,-]?(pazkoa|urtarrila?k?|otsaila?k?|martxoa?k?|apirila?k?|maiatza?k?|ekaina?k?|uztaila?k?|abuztua?k?|iraila?k?|urria?k?|azaroa?k?|abendua?k?)?[ ,-]?([1-9] (astea?n?|hilea?n?|urtea?n?) behin)?$' } }
          - { name: notes, label: Argibideak, type: string }
      - { name: title, label: Izenburua, type: string }
      - { name: description, label: Deskribapena, type: string }
      - { name: image, label: Preview image, type: image }
      - { name: video, label: Youtube, type: string }
      - name: location
        label: Ubicación
        type: object
        fields:
          - { name: title, label: Nombre, type: string }
          - { name: geo, label: Geo, type: string }
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Page config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)