title: 47 Herri
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
image: /media/hero-bg.webp
url: "https://47herri.eus"

plugins:
  - jekyll-feed


goatcounter: '47herri'

modules:
  - seo
  - gospel
  - maps
  - events
  - facade
  - analytics
