title: 47 Herri
description: Nafarroako ipar-mendebaldeko hamar udalerrietako 47 parrokiek osatzen duten pastoral barruti katolikoa gara gu iruñako elizbarrutian.
baseurl: "" # the subpath of your site, e.g. /blog
image: /media/hero-bg.webp
url: "https://47herri.eus"

plugins:
  - jekyll-feed


goatcounter: '47herri'


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "parroquia"

modules:
  - seo
  - gospel
  - maps
  - events
  - facade
  - analytics
  - translate
  - infinite

