name: Notificación Push

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install web-push

      - name: Obtener subscripciones descifradas
        run: curl "https://arrietaeguren.es/subscriptions?token=${{ secrets.NOTIF_TOKEN }}" -o subs.json

      - name: Enviar notificaciones
        env:
          VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
          VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
        run: |
          node <<EOF
          const webpush = require('web-push');
          const subs = require('./subs.json');
          const notifications = require('./notifications.json');

          webpush.setVapidDetails(
            'mailto:admin@47herri.eus',
            process.env.VAPID_PUBLIC,
            process.env.VAPID_PRIVATE
          );

          for (const sub of subs) {
            for (const not of notifications) {
              webpush.sendNotification(sub, JSON.stringify(not))
                .catch(err => console.error('Error con suscripción:', err));
            }
          }
          EOF
