name: Run translate on Markdown Change

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:      # Permite lanzarlo manualmente también

permissions:
  contents: write

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install --production

      - name: Run translate
        run: node _includes/translate.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit changes
        run: |
          git config user.name "translate"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update from GitHub Actions - translate" || echo "No changes to commit"
          git push