name: Run Node Script on Markdown Change

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Run translate
        run: node _includes/translate.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run youtubelist
        run: node _includes/youtubelist.js
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          
