name: Update youtube videos on cron

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora (UTC)
  workflow_dispatch:      # Permite lanzarlo manualmente también

permissions:
  contents: write

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install --production

      - name: Run youtubelist
        run: node _includes/youtubelist.js
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}

      - name: Enviar notificaciones push
        env:
          VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
          VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
          NOTIF_TOKEN: ${{ secrets.NOTIF_TOKEN }}
        run: node notify.js

      - name: Commit changes
        run: |
          git config user.name "youtube"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update from GitHub Actions - youtube" || echo "No changes to commit"
          git push
