name: Update youtube videos on cron

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora (UTC)
  workflow_dispatch:      # Permite lanzarlo manualmente también

permissions:
  contents: write

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install --production

      - name: Run youtubelist
        run: node _includes/youtubelist.js
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}

      - name: Obtener subscripciones descifradas y enviar notificaciones
        env:
          VAPID_PUBLIC: ${{ secrets.VAPID_PUBLIC }}
          VAPID_PRIVATE: ${{ secrets.VAPID_PRIVATE }}
        run: |
          curl "https://arrietaeguren.es/subscriptions?token=${{ secrets.NOTIF_TOKEN }}" -o subs.json
          node <<EOF
          const webpush = require('web-push');
          const subs = require('./subs.json').slice(0, 1);
          const notifications = require('./notifications.json');

          webpush.setVapidDetails(
            'mailto:admin@47herri.eus',
            process.env.VAPID_PUBLIC,
            process.env.VAPID_PRIVATE
          );

          for (const not of notifications) {
              for (const sub of subs) {
              webpush.sendNotification(sub, JSON.stringify(not))
                .catch(err => console.error('Error con suscripción:', err));
            }
          }
          EOF
          rm notifications.json
          rm subs.json

      - name: Commit changes
        run: |
          git config user.name "youtube"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update from GitHub Actions - youtube" || echo "No changes to commit"
          git push
