name: Update youtube videos on cron

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora (UTC)
  workflow_dispatch:      # Permite lanzarlo manualmente también

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install --production

      - name: Run youtubelist
        run: node _includes/youtubelist.js
        env:
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
